/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in new projects. It is checked in here so
// TypeScript understands the Next app before dependencies are installed.
